---
title: "Решение 25-го задания"
geometry: "top=1.5cm,bottom=2.5cm,left=1.5cm,right=1.5cm"
documentclass: extreport
fontsize: 14pt
fontfamily: libertinus
output:
  pdf_document:
    number_sections: false
    latex_engine: xelatex
    pandoc_args: ["--highlight-style=tango"]
    extra_dependencies:
        - hyperref
        - setspace
        - amsmath
linkcolor: blue
fontenc: T2A
lang: ru-RU
babel-lang: russian
---

\tableofcontents
\newpage

\chapter{База про регулярки}

- *Регулярные выражения* (регулярки) - набор символов, помогающий найти информацию в тексте. Проще сказать, шаблоны.
- Например, если вам надо найти все файлы с расширением `png`, то вы, скорее всего, введет `*.png`. Это и есть регулярное выражение.
- Синтакис регулярных выражений везде может быть разным: в Python, в Java, на Windows и т.д.
- https://regex101.com/ - замечательный сайт, на котором можно протестировать свою регулярку. На этом же сайте можно отлаживать свои регулярные выражения (что тоже классно).
- Ну а теперь к базовому синтаксису регулярок:
    - `.` (символ точки) -- любой символ. Буквально любой. Это может быть число, буква, иероглиф и т.д.
    - `\d` -- цифра (одна!).
    - `\w` -- буква (тоже одна!).
    - `+` -- 1 или большее число чего-то. Например, запись `\d+` означает "одна цифра или более".
    - `*` -- 0 или большее число чего-то. Аналогично с предыдущим, только теперь есть и нулевое кол-во.
    - `?` -- 0 или 1. Например, запись `\w?` означает "символ есть или нет".
    - `{n}` -- `n`-количество чего-то. Например, запись `\d{3}` означает "три подряд идущих цифры".
    - `{n,m}` -- длина строки от `n` до `m` (включительно!). Например, запись `\d{3,5}` означает "строка длиной от 3 до 5".
    - `{n,}` -- длина строки от `n` до бесконечности (специфичный символ `+`, так сказать). Например, запись `\w{4,}` означает "строка длиной 4 и более".
    - `[abc]` -- выбор одного из символов, указанных внутри квадратных скобок (в данном случае из символов `abc`). Можно комбинировать со знаками длины (`+*?`). Например, запись `[345]+` означает "одно или более кол-во символов, заключенных в квадртаных скобках".
    - `[a-z]` -- весь английский алфавит в малом регистре.
    - `[A-Z]` -- в верхнем регистре.

\chapter{Полезные функции}
\section{Поиск всех делителей}

```python
def search_divs(x):
    divs = set()

    for i in range(1, int(x**0.5) + 1):
        if x % i == 0:
            divs.add(i)
            divs.add(x // i)

    return divs
```
