---
mainfont: FiraCode Nerd Font
monofont: FiraCode Nerd Font Mono
title: "**Теория для 3, 9 заданий**"
geometry: "top=1.5cm,bottom=2.5cm,left=2cm,right=2cm"
documentclass: extarticle
fontsize: 12pt
output:
  pdf_document:
    number_sections: false
    latex_engine: xelatex
    pandoc_args: ["--highlight-style=tango"]
always_allow_html: yes
---

- **Для 3-го задания**:
    - На сколько изменилом = модуль разности.
    - На сколько увеличилось = "Сколько прибавилось" - "Сколько уменьшилось"
    - На сколько уменьшилось = "Сколько уменьшилось" - "Сколько прибавилось"

- **Для 9-го задания**:
    - Есть условие: "Разбейте четыре числа на две пары, суммы которых будут равны". Лучше отсортировать строчку с числами и сравнить сумму первого и последнего числа и двух других (посередине). Пример:
    ```{python}
    line = [1, 3, 1, 3]
    line.sort()
    if (line[0] + line[3]) == (line[1] + line[2]):
        print(line)
    ```
    - Если нужно найти строку, в которой, например, 6 чисел, и эти числа можно разбить на три пары с одинаковыми числами, то легче отсортировать числа и сравнить их по индексации. Пример:
    ```{python}
    line = [1, 2, 3, 3, 2, 1]
    line.sort()
    if (line[0] == line[1]) and (line[2] == line[3]) and (line[4] == line[5]):
        print(line)
    ```
    - Если нужно найти строку, в которой есть повторяющиеся числа, то здесь легче использовать `set`. Его длину нужно будет просто сравнить с длиной строки. Пример:
    ```{python}
    line = [1, 1, 2, 3, 4]
    if len(set(line)) < len(line):
        print(line)
    ```
    - Если надо сравнить сумму кубов любых двух чисел и квадрат суммы двух оставшихся, то нужно рассматривать худший случай (потому что иначе придется пользоваться `permutations`, а, учитывая большой объем файла, это будет долго). Если для суммы кубов мы возьмем два самых маленьких числа, то это будет самый худший вариант. Если такой случай будет удовлетворять условию, то как бы мы не пытались поменять сумму кубов, она меньше уже не будет (т.к. были взяты самые маленькие значения).
