---
mainfont: AnonymicePro Nerd Font Mono
geometry: "top=1.5cm,bottom=1.5cm,left=2cm,right=2.5cm"
documentclass: extarticle
fontsize: 14pt
output:
  pdf_document:
    number_sections: false
    latex_engine: xelatex
    pandoc_args: ["--highlight-style=tango"]
    extra_dependencies:
        - hyperref
        - setspace
always_allow_html: yes
linkcolor: blue
---
\pagenumbering{gobble}
\title{Теория для 3-го задания}
\pagenumbering{arabic}

\newpage
\renewcommand{\contentsname}{Оглавление}

\doublespacing
\tableofcontents
\renewcommand{\baselinestretch}{1.15}\normalsize

\newpage
\subsection{Введение}
- Некоторые материалы взяты с канала [Евгения Джобса](https://www.youtube.com/@EvgenijJobs).

---

- **IPv4** - 4 байта на адрес
- **IPv16** - 16 байта на адрес

\newpage
\subsection{Про IPv4}
- Для IPv4 используется адрес из 4 чисел, разделенных точкой.
- Каждое число находится в диапазоне от [0; 255].
- Каждое число является восьмибитным, т.е. в случае только 3 чисел в двоичной записи к ней (к записи) будут дописываться нули (в нашем случае, их будет 5).
\vspace{1.5em}
- Чтобы получить двоичную запись IP-адреса, нужно каждое из четырех чисел перевести в двоичную запись.
\vspace{1.5em}
- **Маска сети** - 32-битная последовательность,определяющая часть информации об адресе сети и часть номера компьютера.
- Адрес сети и номер компьютера состоят из 32-битной последовательности.
\vspace{1.5em}
- Типичная задача: "Есть IP-адрес 172.37.201.13 и маска сети 255.255.240.0. Найдите адрес сети и номер компьютера."
- Переведем IP-адрес и маску сети в двоичную запись:

IP-адрес:&nbsp;&nbsp; 10101100.00100101.11001001.00001101

Маска сети: 11111111.11111111.11110000.00000000

- Граница из единиц в маске сети будет адресом сети, а нули - номером компьютера. Эти границы проецируются на IP-адрес:

IP-адрес:&nbsp;&nbsp; \textcolor{blue}{10101100.00100101.1100}\textcolor{red}{1001.00001101}

Маска сети: \textcolor{blue}{11111111.11111111.1111}\textcolor{red}{0000.00000000}

- Теперь остается просто перевести получившиеся числа в десятичную запись, дописав необходимое кол-во нулей:

IP-адрес:&nbsp;&nbsp;\textcolor{blue}{10101100.00100101.1100}0000.00000000 -> 172.37.192.0


Маска сети: 00000000000000000000\textcolor{red}{100100001101} -> 2317

\newpage
\subsection{Про виды адресов}
- В каждой сети есть два зарезервированных адреса:
    - адрес сети
    - широковещательный адрес
- Адрес сети в "области номера компьютера" имеет **все нули**, а широковещательный адрес - **все единицы**.
- Компьютеру, подключенному к сети IPv4, **нельзя выдать один из зарезервированных адресов**.
